# Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fashionLike?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: Mario12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop

    database-plataform: org.hibernate.dialect.MySQL8Dialect
    # SQL

    show-sql: true
    properties:
      hibernate:
        format_sql: false

  # Hibernate configuration
  level:
    org:
      hibernate:
        SQL: debug


server:
  port: 8090

# Security
jwt:
  secret: secret
  expiration: 36000

